export const sectionCopy = {
  about: {
    index: "01",
    title: "About",
    eyebrow: "Driver profile",
    heading: "About",
    accent: "me.",
    tagline: "A compact read on what I care about and how I show up in engineering work.",
  },
  work: {
    index: "02",
    title: "Work",
    eyebrow: "Sanitized case studies",
    heading: "Sanitized",
    accent: "work.",
    tagline: "Real operating context, cleaned of confidential details and shaped around SDE/SRE signal.",
  },
  experience: {
    index: "03",
    title: "Experience",
    eyebrow: "Career history",
    heading: "Professional",
    accent: "timeline.",
    tagline: "Shortened for scanning. Full details on the resume.",
  },
  principles: {
    index: "04",
    title: "Principles",
    eyebrow: "How I think",
    heading: "Engineering",
    accent: "ideology.",
    tagline: "Short version: I like systems that are observable, repeatable, and calm under pressure.",
  },
  skills: {
    index: "05",
    title: "Skills",
    eyebrow: "Technical toolkit",
    heading: "Technical",
    accent: "capabilities.",
    tagline: "A recruiter-readable inventory, with SDE/SRE-relevant strengths brought forward.",
  },
  contact: {
    index: "06",
    title: "Contact",
    eyebrow: "Open channel",
    heading: "Contact",
    accent: "signal.",
    tagline: "Open to SDE and SRE roles where automation, reliability, and careful debugging matter.",
  },
  notes: {
    index: "01",
    title: "Notes",
    eyebrow: "Future work",
    heading: "Engineering",
    accent: "notes.",
    tagline: "A future space for short writeups on debugging, automation, release validation, and reliability thinking.",
  },
};
